

export enum Genre {
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  SELF_HELP = 'SELF_HELP',
  THRILLER = 'THRILLER',
  EDUCATIONAL = 'EDUCATIONAL',
  HISTORICAL_FICTION = 'HISTORICAL_FICTION',
  OTHERS = 'OTHERS',
}
